export interface Disease {
  id: string;
  name: string;
  type: "Viral" | "Bacterial" | "Parasitic" | "Fungal" | "Nutritional";
  severity: "mild" | "serious" | "critical";
  affectedSpecies: string[];
  symptoms: string[];
  visualSigns: string[];
  causes: string[];
  transmission: string[];
  treatment: string[];
  prevention: string[];
  incubation: string;
  mortality: string;
  description: string;
}

export const diseases: Disease[] = [
  {
    id: "newcastle",
    name: "Newcastle Disease",
    type: "Viral",
    severity: "critical",
    affectedSpecies: ["Chickens", "Turkeys", "Pigeons", "Wild birds"],
    description:
      "One of the most devastating poultry diseases worldwide. A highly contagious viral disease affecting the respiratory, nervous, and digestive systems.",
    symptoms: [
      "Twisted neck (torticollis)",
      "Paralysis of legs and wings",
      "Drooping wings",
      "Loss of appetite",
      "Greenish diarrhoea",
      "Gasping and coughing",
      "Sudden drop in egg production",
    ],
    visualSigns: [
      "Swollen head and face",
      "Purple/blue discolouration of comb and wattles",
      "Cloudy or watery eyes",
      "Bird sitting hunched",
    ],
    causes: ["Newcastle disease virus (NDV) — Paramyxovirus"],
    transmission: [
      "Direct contact with infected birds",
      "Contaminated feed, water, equipment",
      "Airborne droplets",
      "Wild birds and migratory species",
    ],
    treatment: [
      "No specific antiviral treatment available",
      "Isolate infected birds immediately",
      "Supportive care: ensure water and electrolytes",
      "Antibiotics to prevent secondary bacterial infections",
      "Report to local veterinary authority (notifiable disease in many countries)",
    ],
    prevention: [
      "Vaccinate flock with ND vaccine (La Sota or Hitchner B1)",
      "Strict biosecurity — limit farm visitors",
      "Quarantine new birds for 2–3 weeks before introduction",
      "Disinfect equipment and housing regularly",
    ],
    incubation: "2–15 days",
    mortality: "Up to 100% in unvaccinated flocks",
  },
  {
    id: "mareks",
    name: "Marek's Disease",
    type: "Viral",
    severity: "serious",
    affectedSpecies: ["Chickens"],
    description:
      "A highly contagious herpesvirus disease causing tumours and nerve damage, primarily in young chickens aged 12–30 weeks.",
    symptoms: [
      "Progressive leg and wing paralysis",
      "Weight loss despite eating",
      "One leg stretched forward, one backward",
      "Drooping wing",
      "Laboured breathing",
      "Vision impairment (grey iris)",
    ],
    visualSigns: [
      "Asymmetric paralysis",
      "Grey or irregular iris (Ocular Marek's)",
      "Skin tumours around feather follicles",
      "Pale comb",
    ],
    causes: ["Marek's disease virus (MDV) — Alphaherpesvirus"],
    transmission: [
      "Highly contagious — spreads via feather dander and dust",
      "Infected birds shed virus for life",
      "Can survive in poultry house dust for months",
    ],
    treatment: [
      "No cure — management is supportive only",
      "Isolate affected birds to reduce stress",
      "Provide easy access to food and water",
      "Cull severely affected birds humanely",
    ],
    prevention: [
      "Vaccinate day-old chicks with Marek's vaccine (HVT or bivalent)",
      "Maintain strict hygiene in hatchery and brooder",
      "Avoid mixing age groups",
      "Use resistant genetic lines where possible",
    ],
    incubation: "3–4 weeks (can be longer)",
    mortality: "10–30% in unvaccinated flocks; higher in severe strains",
  },
  {
    id: "coccidiosis",
    name: "Coccidiosis",
    type: "Parasitic",
    severity: "serious",
    affectedSpecies: ["Chickens", "Turkeys", "Ducks", "Geese"],
    description:
      "A parasitic disease of the intestinal tract caused by Eimeria species. One of the most economically damaging diseases in the poultry industry, especially in broilers.",
    symptoms: [
      "Bloody or mucoid diarrhoea",
      "Lethargy and weakness",
      "Ruffled feathers",
      "Loss of appetite",
      "Pale comb and wattles",
      "Huddling under heat source",
      "Poor weight gain",
    ],
    visualSigns: [
      "Bloody droppings (cecal coccidiosis)",
      "Wet, soiled feathers around vent",
      "Thin, emaciated birds",
    ],
    causes: ["Eimeria species (E. tenella, E. acervulina, E. maxima, others)"],
    transmission: [
      "Ingestion of sporulated oocysts from contaminated litter, feed, or water",
      "Spreads rapidly in wet or overcrowded conditions",
    ],
    treatment: [
      "Amprolium (Corid) in water for 5–7 days",
      "Sulfonamides (sulfadimethoxine)",
      "Toltrazuril or diclazuril (where available)",
      "Supportive vitamins A and K to aid recovery",
      "Clean and dry litter immediately",
    ],
    prevention: [
      "Use coccidiostats in starter feed",
      "Vaccinate with live oocyst vaccine (Coccivac)",
      "Keep litter dry — fix drinker leaks promptly",
      "Avoid overcrowding",
      "All-in/all-out management with thorough cleanout",
    ],
    incubation: "4–7 days",
    mortality: "Variable — up to 50% in severe outbreaks in young chicks",
  },
  {
    id: "avian-influenza",
    name: "Avian Influenza",
    type: "Viral",
    severity: "critical",
    affectedSpecies: ["Chickens", "Turkeys", "Ducks", "Geese", "Wild birds"],
    description:
      "Highly Pathogenic Avian Influenza (HPAI) is a notifiable, devastating disease with near 100% mortality in infected flocks. A major global biosecurity concern.",
    symptoms: [
      "Sudden death with no prior signs (HPAI)",
      "Severe depression and inactivity",
      "Drastic drop in egg production",
      "Respiratory distress",
      "Neurological signs — incoordination",
      "Watery green diarrhoea",
    ],
    visualSigns: [
      "Swollen head, face, eyelids",
      "Purple/black discolouration of comb, wattles, legs",
      "Haemorrhages on legs and feet",
      "Discharge from eyes and nostrils",
    ],
    causes: ["Influenza A virus — H5 and H7 strains (HPAI); other strains (LPAI)"],
    transmission: [
      "Direct contact with infected birds or their secretions",
      "Contaminated equipment, vehicles, clothing",
      "Wild migratory waterfowl are primary reservoir",
      "Airborne over short distances",
    ],
    treatment: [
      "No treatment — all infected and exposed birds must be culled",
      "Immediately report to veterinary authorities",
      "Impose strict quarantine on affected farm and surroundings",
      "Full farm disinfection and downtime required",
    ],
    prevention: [
      "Strict biosecurity — limit wild bird access to housing and water sources",
      "Do not share equipment between farms",
      "Monitor flock daily — report sudden deaths",
      "Vaccination available in some countries (consult local authority)",
    ],
    incubation: "1–5 days (HPAI); up to 14 days (LPAI)",
    mortality: "Near 100% for HPAI H5N1",
  },
  {
    id: "infectious-bronchitis",
    name: "Infectious Bronchitis",
    type: "Viral",
    severity: "serious",
    affectedSpecies: ["Chickens"],
    description:
      "A highly contagious respiratory disease of chickens caused by a coronavirus. One of the most common respiratory diseases globally, with many variants.",
    symptoms: [
      "Gasping, coughing, sneezing",
      "Nasal discharge and watery eyes",
      "Rales (rattling breath sounds)",
      "Reduced feed and water consumption",
      "Significant drop in egg production",
      "Misshapen, soft-shelled, or rough eggs",
    ],
    visualSigns: [
      "Hunched posture with neck pulled in",
      "Wet eyes and nostrils",
      "Pale birds in severe cases",
    ],
    causes: ["Infectious bronchitis virus (IBV) — Gammacoronavirus"],
    transmission: [
      "Highly airborne — spreads within hours in a flock",
      "Contaminated equipment, clothing, vehicles",
      "Recovered birds may shed virus for weeks",
    ],
    treatment: [
      "No specific antiviral treatment",
      "Raise house temperature by 2–3°C to reduce stress",
      "Antibiotics to control secondary bacterial infections (E. coli, Mycoplasma)",
      "Ensure good ventilation without draughts",
      "Electrolytes and vitamins in water",
    ],
    prevention: [
      "Vaccinate with live attenuated IBV vaccine (Mass, H120, 4/91 strains)",
      "Strict all-in/all-out management",
      "Thorough disinfection between flocks",
      "Reduce stress factors — overcrowding, poor ventilation",
    ],
    incubation: "18–36 hours",
    mortality: "Low in adults; can be higher in young chicks with concurrent infections",
  },
  {
    id: "fowl-pox",
    name: "Fowl Pox",
    type: "Viral",
    severity: "mild",
    affectedSpecies: ["Chickens", "Turkeys", "Pigeons"],
    description:
      "A slow-spreading viral disease with two forms: dry pox (skin lesions) and wet pox (diphtheritic lesions in mouth/throat). Rarely fatal but causes significant production losses.",
    symptoms: [
      "Wart-like nodules on comb, wattles, face",
      "Reduced feed intake",
      "Drop in egg production",
      "Wet form: gasping and difficulty swallowing",
      "Wet form: white or yellow plaques in mouth and throat",
    ],
    visualSigns: [
      "Raised, crusty scabs on comb and wattles",
      "Lesions around eyes — may cause blindness",
      "Yellow-white cankers in mouth (wet form)",
    ],
    causes: ["Fowlpox virus — Avipoxvirus"],
    transmission: [
      "Mosquito bites (primary vector)",
      "Direct contact with infected birds",
      "Skin wounds and abrasions",
      "Contaminated equipment",
    ],
    treatment: [
      "No specific treatment",
      "Soft, easily accessible feed and water for wet form birds",
      "Remove loose scabs and apply iodine or gentian violet",
      "Antibiotics for secondary infections",
      "Control mosquito populations on farm",
    ],
    prevention: [
      "Vaccinate using wing-web stab method",
      "Mosquito control — drainage, screens, repellents",
      "Isolate newly introduced birds",
    ],
    incubation: "4–10 days",
    mortality: "Low (dry form); moderate if wet form causes suffocation in young birds",
  },
  {
    id: "salmonellosis",
    name: "Salmonellosis",
    type: "Bacterial",
    severity: "serious",
    affectedSpecies: ["Chickens", "Turkeys", "Ducks"],
    description:
      "A bacterial infection causing pullorum disease or fowl typhoid in poultry, and a major zoonotic concern. Responsible for significant chick mortality and food safety issues.",
    symptoms: [
      "Sudden death in chicks under 2 weeks",
      "White or yellow pasty droppings",
      "Chicks huddling near heat",
      "Laboured breathing",
      "Swollen joints",
      "Blindness in some cases",
    ],
    visualSigns: [
      "Pasted vent (dried droppings blocking vent)",
      "Droopy, sleepy-looking chicks",
      "Swollen hock joints",
    ],
    causes: ["Salmonella Pullorum, S. Gallinarum, S. Typhimurium, S. Enteritidis"],
    transmission: [
      "Vertical transmission — infected hen to egg",
      "Contaminated hatchery environment",
      "Contaminated feed (animal by-products)",
      "Rodents and wild birds",
    ],
    treatment: [
      "Enrofloxacin or ciprofloxacin (consult vet — resistance is a concern)",
      "Trimethoprim-sulfamethoxazole",
      "Supportive warmth for chicks",
      "Electrolyte therapy",
      "Note: Treatment does not eliminate carrier state",
    ],
    prevention: [
      "Source chicks from certified Salmonella-free hatcheries",
      "Rodent control programme",
      "Thorough cleaning and disinfection between batches",
      "Vaccination available for S. Enteritidis in layers",
      "Avoid feeding untreated animal by-products",
    ],
    incubation: "Variable — days to weeks",
    mortality: "Up to 100% in young chicks; lower in adults",
  },
  {
    id: "aspergillosis",
    name: "Aspergillosis",
    type: "Fungal",
    severity: "serious",
    affectedSpecies: ["Chickens", "Turkeys", "Ducks", "Geese"],
    description:
      "A fungal respiratory disease caused by Aspergillus fumigatus. Also called brooder pneumonia in young chicks. Caused by mouldy litter or feed.",
    symptoms: [
      "Gasping and laboured breathing",
      "Rapid breathing",
      "Listlessness and weakness",
      "Loss of appetite",
      "Thirst increase",
      "Nervous signs in chronic cases (head tilt, convulsions)",
    ],
    visualSigns: [
      "Open-mouth breathing",
      "Blue/purple tinge to comb (cyanosis)",
      "Emaciation in chronic cases",
    ],
    causes: ["Aspergillus fumigatus (primary); A. flavus, A. niger"],
    transmission: [
      "Inhalation of fungal spores from mouldy litter, bedding, or feed",
      "Not directly contagious bird-to-bird",
      "Contaminated hatchery incubators",
    ],
    treatment: [
      "Remove source of mould immediately",
      "Itraconazole or voriconazole (expensive, use for valuable birds)",
      "Copper sulphate in water (1:2000 solution) — supportive",
      "Improve ventilation drastically",
    ],
    prevention: [
      "Never use mouldy litter, hay, or feed",
      "Store feed in dry, well-ventilated areas",
      "Maintain dry litter — fix water leaks promptly",
      "Good ventilation in brooders and houses",
      "Regular litter inspection and replacement",
    ],
    incubation: "2–7 days after heavy exposure",
    mortality: "High in acute outbreaks in young chicks; variable in adults",
  },
  {
    id: "bumblefoot",
    name: "Bumblefoot",
    type: "Bacterial",
    severity: "mild",
    affectedSpecies: ["Chickens", "Ducks", "Turkeys"],
    description:
      "A staph infection of the foot pad, usually starting from a wound or abrasion. Common in heavy breeds and birds on hard or wire floors.",
    symptoms: [
      "Limping or favouring one leg",
      "Reluctance to walk or stand",
      "Swollen, hot foot pad",
      "Black scab on the bottom of foot",
    ],
    visualSigns: [
      "Swollen, red, or black foot pad",
      "Hard lump or abscess on sole of foot",
      "Visible wound or scab",
    ],
    causes: ["Staphylococcus aureus (primary); other bacteria through wound entry"],
    transmission: [
      "Not contagious — individual injury-based infection",
      "Wire or rough flooring causing foot abrasions",
      "Obesity in heavy breeds",
      "Vitamin A or biotin deficiency",
    ],
    treatment: [
      "Soak foot in warm Epsom salt solution for 10–15 minutes",
      "Remove scab carefully and clean wound",
      "Apply antibiotic ointment (neomycin/bacitracin)",
      "Bandage foot and change dressing daily",
      "Systemic antibiotics for severe cases (amoxicillin)",
      "Surgical debridement for large abscesses",
    ],
    prevention: [
      "Provide soft, dry litter — avoid wire floors for heavy breeds",
      "Maintain healthy body weight",
      "Inspect feet weekly, treat wounds promptly",
      "Ensure adequate vitamins A and biotin in diet",
    ],
    incubation: "Days to weeks after initial injury",
    mortality: "Rarely fatal if treated early",
  },
  {
    id: "infectious-bursal",
    name: "Gumboro Disease",
    type: "Viral",
    severity: "serious",
    affectedSpecies: ["Chickens"],
    description:
      "Infectious Bursal Disease (IBD) attacks the immune system of young chickens, making them susceptible to other infections. Most damaging in birds 3–6 weeks old.",
    symptoms: [
      "Sudden onset — many birds affected simultaneously",
      "Whitish watery diarrhoea",
      "Severe depression and inactivity",
      "Ruffled feathers and huddling",
      "Picking at their own vent",
      "Dehydration",
    ],
    visualSigns: [
      "Wet, soiled feathers around vent",
      "Pale, anaemic appearance",
      "Haemorrhages in thigh muscles (post-mortem)",
    ],
    causes: ["Infectious Bursal Disease Virus (IBDV) — Birnavirus"],
    transmission: [
      "Highly resistant virus — survives months in environment",
      "Contaminated feed, water, litter, equipment",
      "Fomites including boots and vehicles",
    ],
    treatment: [
      "No specific treatment",
      "Electrolytes and vitamins in water",
      "Reduce stress — optimise temperature and stocking density",
      "Antibiotics for secondary infections",
    ],
    prevention: [
      "Vaccinate breeders — maternal antibody protection",
      "Vaccinate chicks at 2–3 weeks with live or intermediate vaccine",
      "Thorough disinfection — use chlorine or formalin",
      "All-in/all-out management",
    ],
    incubation: "2–3 days",
    mortality: "Up to 30% in susceptible flocks; survivors have compromised immunity",
  },
];